Feature/dops 1658/setup cd
sora-xor/sora-subquery pull request #105
Opened 2022-04-12 13:32 UTC by f33r0

2022-04-13 11:23 UTC, Cre-eD commented on Jenkinsfile
> +                           --branch develop \
it will redeploy dev env, how will you redeploy test env?

2022-04-13 11:24 UTC, Cre-eD commented on Jenkinsfile
> -)
You broke the CI for the app, but should have created a new Jenkisfile-onfinality file

2022-04-20 08:57 UTC, Cre-eD commented on Jenkinsfile-onfinality
> +String jobList           = '../deploy/sora2-' + targetEnvironment
![image](https://user-images.githubusercontent.com/45072677/164191064-d6a92f5f-6995-4980-a464-dd8984b17a5a.png)

2022-04-20 08:58 UTC, Cre-eD commented on Jenkinsfile-onfinality
> +String jobList           = '../deploy/sora2-' + targetEnvironment
```suggestion
String jobList           = '../sora2-' + targetEnvironment
```

2022-04-20 08:59 UTC, Cre-eD requested changes
fix comments

2022-04-21 05:54 UTC, f33r0 commented on Jenkinsfile-onfinality
> +String jobList           = '../deploy/sora2-' + targetEnvironment
fix into jenkins

2022-04-25 12:05 UTC, Cre-eD approved these changes

2022-04-26 05:40 UTC, merged