[Duty]: Fix CD for subquery
sora-xor/sora-subquery pull request #110
Opened 2022-05-05 09:16 UTC by f33r0

# Task

[Duty]: Fix CD for subquery

## Changes

1. Change ubuntu image version
2. Change sora2 test instance

## Author

Signed-off-by: name <zaporozhets@soramitsu.co.jp>

2022-05-05 10:09 UTC, ahmedelkashev approved these changes

2022-05-06 01:40 UTC, wpi86 requested changes

2022-05-06 01:40 UTC, wpi86 commented on Jenkinsfile-onfinality
> +String envImageName      = 'ubuntu:bionic'
why not focal?

2022-05-11 05:32 UTC, Cre-eD approved these changes

2022-05-12 01:23 UTC, wpi86 approved these changes

2022-05-12 05:36 UTC, merged