PW-404: Referral Handlers
sora-xor/sora-subquery pull request #70
Opened 2022-01-26 09:02 UTC by alexnatalia

# Task

[PW-404]: Referral system support via web app

## Changes

* Added Referral Handlers for History

[PW-404]: https://soramitsu.atlassian.net/browse/PW-404

2022-01-26 09:15 UTC, RustemYuzlibaev approved these changes

2022-01-26 09:42 UTC, Nikita-Polyakov approved these changes

2022-01-26 10:56 UTC, pgolovkin approved these changes

2022-01-26 12:35 UTC, bgodlin requested changes
All new added `.ts` files will not be handling as there are not appended to the `src/mapping/index.ts`. Still, should we aggregate all functions in new files to the single file, called, for instance, `"referralSystemHandlers.ts"`?

Additionally, all new extrinsics will be saved as the HistoryElement entity, which will be storing all other handled extrinsics (transafers, swaps and other displayed at `#account` page) in the same table at the db level - thus, there may be performance issues. Thus, I suppose, to increase the performance, it would be reasonable to assign a separate entity for every entity that will have a separate view in final UI. For instance, if we're having a view that will list of reserve and unreserve activities, the most optimized way will be to group the corresponding extrinsics in the separate entity.

2022-01-26 12:35 UTC, bgodlin commented on schema.graphql
> +type ReferralUreserve @entity {
A small typo here

2022-01-26 12:35 UTC, bgodlin commented on src/mappings/referrerRewardHandler.ts
> +			data: [referral, referrer, amount],
Seems like we have a definition error in https://soramitsu.atlassian.net/browse/PW-404

2022-01-26 12:35 UTC, bgodlin commented on schema.graphql
> +type SetReferral @entity {
All new added entities are not used in the mapping files - then, I guess, there is no need adding the here

2022-01-28 10:34 UTC, bgodlin approved these changes

2022-01-28 10:44 UTC, merged